### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by helish88** [fxcvd/AdvancedPresence#2]
Unresolved reference 'Presence' in app.py

**Comment by silverfox0000** [comment]
Он же писал что работает только **макОС** тк это AppleScript + Python

**Comment by helish88** [comment]
так такой переменной нет, такого класса нет и че ты тут делаешь, шпион?

**Comment by silverfox0000** [comment]
А и да дополнения вот. [ТЫК](https://github.com/fxcvd/AdvancedPresence/blob/871b983a4db57b6c433d48f7ce6e674f21cba8ce/assets/requirements.txt)
